### ISSUE TITLE
我看到最新版本是 0.0.13

### ISSUE THREAD

**Issue by yolio2003** [willerce/gulp-tmtsprite#3]
npm cnpm 都试过 为何都是 0.0.11
该怎么升级
搞定了，是package.json里面写死了

**Comment by willerce** [comment]
@tcdona 你指的是哪个版本？

**Comment by yolio2003** [comment]
我之前直接 npm install 了，现在好啦。

雪碧图文件夹只能是 slice > sprite ?
我们的grunt是 assets > img 呢

**Comment by willerce** [comment]
@tcdona 是的，目前只支持 slice > sprite

**Comment by yolio2003** [comment]
了解啦
